project:
  type: website
  output-dir: docs

website:
  title: "The Within Family Consortium"
  twitter-card: 
    site: "@nm_davies"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - cohorts.qmd
      - projects.qmd
      - proposals.qmd
      - outputs.qmd
  page-footer: |
    <hr></hr>
    <table style="width: 100%;">
    <tr>
      <td style="text-align: left; vertical-align: top;">
        <p>Contact Information:<br/>
        <strong>Email:</strong> <a href="mailti:neil.m.davies@ucl.ac.uk">neil.m.davies@ucl.ac.uk</a>
      </p>
      </td>
      <td style="text-align: left; vertical-align: top;">
        <a href="https://www.bristol.ac.uk/ieu/" target="_blank">
          <img src="assets/mrc-ieu-logo.png" width="200">
        </a><br/></td>
      <td style="text-align: left; vertical-align: top;">
        <a href="https://www.bristol.ac.uk/" target="_blank">
          <img src="assets/bristol.png" width="200">
        </a>
      </td>
    </tr>
    </table>
format:
  html:
    theme: simplex
    css: styles.css
    toc: true



